name: gm-dev
services:
  # [gm-discord]
  discord:
    container_name: "gm-dev-discord"
    image: gm-discord:dev
    build:
      dockerfile: "./Dockerfile"
    ports:
      - "5050:5050"
    tty: true
    env_file:
      - "./.env"
